flowchart LR
subgraph Network[Network]
  cfn_CloudFrontOAC["CloudFrontOAC\nOriginAccessControl"]
  cfn_Distribution["Distribution\nDistribution"]
end
subgraph Security[Security]
  cfn_WafAcl["WafAcl\nWebACL"]
end
subgraph Storage[Storage]
  cfn_LogsBucket["LogsBucket\nBucket"]
  cfn_SiteBucket["SiteBucket\nBucket"]
  cfn_SiteBucketPublicAccessBlock["SiteBucketPublicAccessBlock\nBucketPublicAccessBlock"]
end
cfn_CloudFrontOAC --> cfn_Distribution
cfn_LogsBucket --> cfn_Distribution
cfn_LogsBucket --> cfn_SiteBucket
cfn_SiteBucket --> cfn_Distribution
cfn_SiteBucket --> cfn_SiteBucketPublicAccessBlock
cfn_WafAcl --> cfn_Distribution
