name: Auto Architecture Diagram
description: Generate professional architecture diagrams from IaC changes (Mermaid + PNG/SVG/JPEG with icons).
author: suryakumaran

inputs:
  changed_files:
    description: Space/newline-separated list of changed IaC files.
    required: true
  iac_root:
    description: Root directory to read IaC files from.
    required: false
    default: .
  direction:
    description: Diagram direction (LR|RL|TB|BT).
    required: false
    default: LR
  mode:
    description: Generator mode (static|ai).
    required: false
    default: static
  model:
    description: AI model name (only used when mode=ai).
    required: false
    default: gpt-4o-mini
  render_layout:
    description: Icon render layout (lanes|providers).
    required: false
    default: lanes
  render_bg:
    description: PNG/SVG background (transparent|white). JPEG is always white.
    required: false
    default: transparent
  publish_enabled:
    description: Whether to write outputs into publish.paths from .auto-arch-diagram.yml.
    required: false
    default: 'false'
  out_dir:
    description: Output directory for artifacts.
    required: false
    default: artifacts

outputs:
  md_path:
    description: Path to generated markdown.
    value: ${{ steps.out.outputs.md_path }}
  mmd_path:
    description: Path to generated mermaid.
    value: ${{ steps.out.outputs.mmd_path }}
  png_path:
    description: Path to generated PNG.
    value: ${{ steps.out.outputs.png_path }}
  jpg_path:
    description: Path to generated JPEG.
    value: ${{ steps.out.outputs.jpg_path }}
  svg_path:
    description: Path to generated SVG.
    value: ${{ steps.out.outputs.svg_path }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Graphviz (Linux)
      shell: bash
      run: |
        if command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y graphviz
        fi

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"

    - name: Generate diagrams
      shell: bash
      env:
        AUTO_ARCH_MODE: ${{ inputs.mode }}
        AUTO_ARCH_MODEL: ${{ inputs.model }}
        AUTO_ARCH_DIRECTION: ${{ inputs.direction }}
        AUTO_ARCH_RENDER_LAYOUT: ${{ inputs.render_layout }}
        AUTO_ARCH_RENDER_BG: ${{ inputs.render_bg }}
        AUTO_ARCH_PUBLISH_ENABLED: ${{ inputs.publish_enabled }}
      run: |
        OUT_DIR="${{ inputs.out_dir }}"
        mkdir -p "${OUT_DIR}"

        python "${GITHUB_ACTION_PATH}/tools/generate_arch_diagram.py" \
          --iac-root "${{ inputs.iac_root }}" \
          --changed-files "${{ inputs.changed_files }}" \
          --out-md "${OUT_DIR}/architecture-diagram.md" \
          --out-mmd "${OUT_DIR}/architecture-diagram.mmd" \
          --out-png "${OUT_DIR}/architecture-diagram.png" \
          --out-jpg "${OUT_DIR}/architecture-diagram.jpg" \
          --out-svg "${OUT_DIR}/architecture-diagram.svg"

    - name: Export outputs
      id: out
      shell: bash
      run: |
        OUT_DIR="${{ inputs.out_dir }}"
        echo "md_path=${OUT_DIR}/architecture-diagram.md" >> "$GITHUB_OUTPUT"
        echo "mmd_path=${OUT_DIR}/architecture-diagram.mmd" >> "$GITHUB_OUTPUT"
        echo "png_path=${OUT_DIR}/architecture-diagram.png" >> "$GITHUB_OUTPUT"
        echo "jpg_path=${OUT_DIR}/architecture-diagram.jpg" >> "$GITHUB_OUTPUT"
        echo "svg_path=${OUT_DIR}/architecture-diagram.svg" >> "$GITHUB_OUTPUT"
