flowchart LR
subgraph all_AWS[AWS]
  subgraph vpc_aws_vpc_dr[VPC
dr]
    tf_aws_vpc_dr["aws_vpc.dr"]
    subgraph subnet_aws_subnet_dr_private_a[Subnet
dr private a (Private)]
      tf_aws_subnet_dr_private_a["aws_subnet.dr_private_a"]
      tf_aws_db_subnet_group_dr_db["aws_db_subnet_group.dr_db"]
      tf_aws_instance_app_dr["aws_instance.app_dr"]
      tf_aws_rds_cluster_app_db_dr["aws_rds_cluster.app_db_dr"]
    end
  end
  subgraph vpc_aws_vpc_primary[VPC
primary]
    tf_aws_vpc_primary["aws_vpc.primary"]
    subgraph subnet_aws_subnet_primary_private_a[Subnet
primary… (Private)]
      tf_aws_subnet_primary_private_a["aws_subnet.primary_private_a"]
      tf_aws_db_subnet_group_primary_db["aws_db_subnet_group.primary_db"]
      tf_aws_instance_app_primary["aws_instance.app_primary"]
      tf_aws_rds_cluster_app_db_primary["aws_rds_cluster.app_db_primary"]
      tf_aws_rds_cluster_read_replica_link["aws_rds_cluster.read_replica_link"]
    end
    tf_aws_security_group_app_sg["aws_security_group.app_sg"]
  end
  tf_aws_vpc_peering_connection_primary_to_dr["aws_vpc_peering_connection.primary_to_dr"]
end
tf_aws_db_subnet_group_dr_db --> tf_aws_rds_cluster_app_db_dr
tf_aws_db_subnet_group_primary_db --> tf_aws_rds_cluster_app_db_primary
tf_aws_db_subnet_group_primary_db --> tf_aws_rds_cluster_read_replica_link
tf_aws_rds_cluster_app_db_primary --> tf_aws_rds_cluster_read_replica_link
tf_aws_security_group_app_sg --> tf_aws_instance_app_primary
tf_aws_subnet_dr_private_a --> tf_aws_db_subnet_group_dr_db
tf_aws_subnet_dr_private_a --> tf_aws_instance_app_dr
tf_aws_subnet_primary_private_a --> tf_aws_db_subnet_group_primary_db
tf_aws_subnet_primary_private_a --> tf_aws_instance_app_primary
tf_aws_vpc_dr --> tf_aws_subnet_dr_private_a
tf_aws_vpc_dr --> tf_aws_vpc_peering_connection_primary_to_dr
tf_aws_vpc_primary --> tf_aws_security_group_app_sg
tf_aws_vpc_primary --> tf_aws_subnet_primary_private_a
tf_aws_vpc_primary --> tf_aws_vpc_peering_connection_primary_to_dr
