flowchart AUTO
subgraph AWS[AWS]
  tf_aws_eks_cluster_k8s["aws_eks_cluster.k8s"]
  tf_aws_instance_web["aws_instance.web"]
  tf_aws_security_group_web["aws_security_group.web"]
  tf_aws_subnet_public["aws_subnet.public"]
  tf_aws_vpc_main["aws_vpc.main"]
end
subgraph AZURERM[AZURERM]
  tf_azurerm_kubernetes_cluster_aks["azurerm_kubernetes_cluster.aks"]
  tf_azurerm_linux_virtual_machine_vm["azurerm_linux_virtual_machine.vm"]
  tf_azurerm_network_security_group_nsg["azurerm_network_security_group.nsg"]
  tf_azurerm_resource_group_rg["azurerm_resource_group.rg"]
  tf_azurerm_subnet_subnet["azurerm_subnet.subnet"]
  tf_azurerm_virtual_network_vnet["azurerm_virtual_network.vnet"]
end
subgraph GOOGLE[GOOGLE]
  tf_google_compute_firewall_web["google_compute_firewall.web"]
  tf_google_compute_instance_vm["google_compute_instance.vm"]
  tf_google_compute_network_vpc["google_compute_network.vpc"]
  tf_google_container_cluster_gke["google_container_cluster.gke"]
end
subgraph IBM[IBM]
  tf_ibm_is_instance_vm["ibm_is_instance.vm"]
  tf_ibm_is_vpc_vpc["ibm_is_vpc.vpc"]
end
subgraph OCI[OCI]
  tf_oci_core_instance_vm["oci_core_instance.vm"]
  tf_oci_core_subnet_subnet["oci_core_subnet.subnet"]
  tf_oci_core_vcn_vcn["oci_core_vcn.vcn"]
end
tf_aws_security_group_web --> tf_aws_instance_web
tf_aws_subnet_public --> tf_aws_eks_cluster_k8s
tf_aws_subnet_public --> tf_aws_instance_web
tf_aws_vpc_main --> tf_aws_eks_cluster_k8s
tf_aws_vpc_main --> tf_aws_security_group_web
tf_aws_vpc_main --> tf_aws_subnet_public
tf_azurerm_resource_group_rg --> tf_azurerm_kubernetes_cluster_aks
tf_azurerm_resource_group_rg --> tf_azurerm_linux_virtual_machine_vm
tf_azurerm_resource_group_rg --> tf_azurerm_network_security_group_nsg
tf_azurerm_resource_group_rg --> tf_azurerm_subnet_subnet
tf_azurerm_resource_group_rg --> tf_azurerm_virtual_network_vnet
tf_azurerm_subnet_subnet --> tf_azurerm_linux_virtual_machine_vm
tf_azurerm_virtual_network_vnet --> tf_azurerm_kubernetes_cluster_aks
tf_azurerm_virtual_network_vnet --> tf_azurerm_subnet_subnet
tf_google_compute_firewall_web --> tf_google_compute_instance_vm
tf_google_compute_network_vpc --> tf_google_compute_firewall_web
tf_google_compute_network_vpc --> tf_google_compute_instance_vm
tf_google_compute_network_vpc --> tf_google_container_cluster_gke
tf_ibm_is_vpc_vpc --> tf_ibm_is_instance_vm
tf_oci_core_subnet_subnet --> tf_oci_core_instance_vm
tf_oci_core_vcn_vcn --> tf_oci_core_subnet_subnet
