AWSTemplateFormatVersion: '2010-09-09'
Description: Test CloudFormation template

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-test-bucket
  
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-test-function
      Runtime: python3.9
      Handler: index.handler
      Code:
        ZipFile: |
          def handler(event, context):
              return 'Hello'
  
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-test-api
