"""Mock Configuration Generator for TerraVision Integration."""

import json
import yaml
from pathlib import Path
from typing import Dict, Any, Optional
from dataclasses import dataclass, asdict


@dataclass
class MockConfigProfile:
    """Profile for different mock configuration scenarios."""
    name: str
    description: str
    aws_region: str = "us-east-1"
    azure_location: str = "eastus"
    gcp_region: str = "us-central1"
    oci_region: str = "us-ashburn-1"
    ibm_region: str = "us-south"
    
    # Security level (low, medium, high) affects mock complexity
    security_level: str = "medium"
    
    # Environment type (development, staging, production)
    environment: str = "development"


class MockConfigGenerator:
    """Generate comprehensive mock configurations for different scenarios."""
    
    def __init__(self):
        self.profiles = self._load_default_profiles()
    
    def _load_default_profiles(self) -> Dict[str, MockConfigProfile]:
        """Load default mock configuration profiles."""
        return {
            "development": MockConfigProfile(
                name="development",
                description="Development environment with minimal security",
                aws_region="us-east-1",
                azure_location="eastus",
                gcp_region="us-central1",
                security_level="low",
                environment="development"
            ),
            "staging": MockConfigProfile(
                name="staging",
                description="Staging environment with moderate security",
                aws_region="us-west-2",
                azure_location="westus",
                gcp_region="us-west1",
                security_level="medium",
                environment="staging"
            ),
            "production": MockConfigProfile(
                name="production",
                description="Production environment with high security",
                aws_region="us-gov-west-1",
                azure_location="usgovvirginia",
                gcp_region="us-central1",
                security_level="high",
                environment="production"
            ),
            "multi-cloud": MockConfigProfile(
                name="multi-cloud",
                description="Multi-cloud setup across different regions",
                aws_region="us-east-1",
                azure_location="westeurope",
                gcp_region="europe-west1",
                oci_region="eu-frankfurt-1",
                ibm_region="eu-de",
                security_level="high",
                environment="production"
            )
        }
    
    def generate_terraform_providers(self, profile: MockConfigProfile, output_path: Path) -> None:
        """Generate Terraform provider configuration for a specific profile."""
        
        # Generate mock credentials based on security level
        mock_suffix = self._get_mock_suffix(profile.security_level)
        
        provider_config = f"""# Terraform Provider Configuration for {profile.name.upper()} Environment
# Profile: {profile.description}
# Security Level: {profile.security_level}
# Generated by auto-arch-diagram mock configuration generator

# AWS Provider Configuration
provider "aws" {{
  region                      = "{profile.aws_region}"
  access_key                  = "mock_access_key_{mock_suffix}"
  secret_key                  = "mock_secret_key_{mock_suffix}"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  
  default_tags {{
    Environment = "{profile.environment}"
    GeneratedBy = "auto-arch-diagram"
    SecurityLevel = "{profile.security_level}"
  }}
}}

# Azure Provider Configuration
provider "azurerm" {{
  subscription_id             = "mock_subscription_id_{mock_suffix}"
  client_id                  = "mock_client_id_{mock_suffix}"
  client_secret              = "mock_client_secret_{mock_suffix}"
  tenant_id                  = "mock_tenant_id_{mock_suffix}"
  skip_provider_registration = true
  
  features {{
    resource_group {{
      prevent_group_name_collision = false
    }}
  }}
  
  default_tags {{
    Environment = "{profile.environment}"
    GeneratedBy = "auto-arch-diagram"
    SecurityLevel = "{profile.security_level}"
  }}
}}

# Google Cloud Provider Configuration
provider "google" {{
  project     = "mock_project_{mock_suffix}"
  credentials = "mock_credentials_{mock_suffix}.json"
  region      = "{profile.gcp_region}"
  
  default_tags {{
    Environment = "{profile.environment}"
    GeneratedBy = "auto-arch-diagram"
    SecurityLevel = "{profile.security_level}"
  }}
}}

# Oracle Cloud Infrastructure Provider Configuration
provider "oci" {{
  user_id        = "mock_user_id_{mock_suffix}"
  fingerprint    = "mock_fingerprint_{mock_suffix}"
  private_key    = "mock_private_key_{mock_suffix}"
  tenancy        = "mock_tenancy_{mock_suffix}"
  region         = "{profile.oci_region}"
  skip_credentials_validation = true
  
  default_tags {{
    Environment = "{profile.environment}"
    GeneratedBy = "auto-arch-diagram"
    SecurityLevel = "{profile.security_level}"
  }}
}}

# IBM Cloud Provider Configuration
provider "ibm" {{
  region           = "{profile.ibm_region}"
  ibmcloud_api_key = "mock_api_key_{mock_suffix}"
  resource_group   = "mock_resource_group_{mock_suffix}"
  
  default_tags {{
    Environment = "{profile.environment}"
    GeneratedBy = "auto-arch-diagram"
    SecurityLevel = "{profile.security_level}"
  }}
}}

# Terraform Configuration
terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }}
    google = {{
      source  = "hashicorp/google"
      version = "~> 4.0"
    }}
    oci = {{
      source  = "oracle/oci"
      version = "~> 4.0"
    }}
    ibm = {{
      source  = "IBM-Cloud/ibm"
      version = "~> 1.0"
    }}
  }}
  
  required_version = ">= 1.0"
}}
"""
        
        output_path.write_text(provider_config)
        print(f"✅ Generated Terraform providers for profile '{profile.name}'")
        print(f"   Output: {output_path}")
        print(f"   Security Level: {profile.security_level}")
        print(f"   Environment: {profile.environment}")
    
    def generate_github_actions_env(self, profile: MockConfigProfile, output_path: Path) -> None:
        """Generate GitHub Actions environment file."""
        
        mock_suffix = self._get_mock_suffix(profile.security_level)
        
        env_config = f"""# GitHub Actions Environment Variables for {profile.name.upper()}
# Profile: {profile.description}
# Security Level: {profile.security_level}
# Generated by auto-arch-diagram mock configuration generator

# AWS Environment Variables
AWS_ACCESS_KEY_ID=mock_access_key_{mock_suffix}
AWS_SECRET_ACCESS_KEY=mock_secret_key_{mock_suffix}
AWS_DEFAULT_REGION={profile.aws_region}
TF_VAR_access_key=mock_access_key_{mock_suffix}
TF_VAR_secret_key=mock_secret_key_{mock_suffix}
TF_VAR_region={profile.aws_region}

# Azure Environment Variables
ARM_SUBSCRIPTION_ID=mock_subscription_id_{mock_suffix}
ARM_CLIENT_ID=mock_client_id_{mock_suffix}
ARM_CLIENT_SECRET=mock_client_secret_{mock_suffix}
ARM_TENANT_ID=mock_tenant_id_{mock_suffix}
TF_VAR_subscription_id=mock_subscription_id_{mock_suffix}
TF_VAR_client_id=mock_client_id_{mock_suffix}
TF_VAR_client_secret=mock_client_secret_{mock_suffix}
TF_VAR_tenant_id=mock_tenant_id_{mock_suffix}

# Google Cloud Environment Variables
GOOGLE_PROJECT_ID=mock_project_{mock_suffix}
GOOGLE_APPLICATION_CREDENTIALS=mock_credentials_{mock_suffix}.json
TF_VAR_project_id=mock_project_{mock_suffix}
TF_VAR_credentials=mock_credentials_{mock_suffix}.json

# Oracle Cloud Infrastructure Environment Variables
OCI_USER_ID=mock_user_id_{mock_suffix}
OCI_FINGERPRINT=mock_fingerprint_{mock_suffix}
OCI_PRIVATE_KEY=mock_private_key_{mock_suffix}
OCI_TENANCY=mock_tenancy_{mock_suffix}
TF_VAR_user_id=mock_user_id_{mock_suffix}
TF_VAR_fingerprint=mock_fingerprint_{mock_suffix}
TF_VAR_private_key=mock_private_key_{mock_suffix}
TF_VAR_tenancy=mock_tenancy_{mock_suffix}

# IBM Cloud Environment Variables
IBMCLOUD_API_KEY=mock_api_key_{mock_suffix}
IC_API_KEY=mock_api_key_{mock_suffix}
TF_VAR_api_key=mock_api_key_{mock_suffix}
TF_VAR_resource_group=mock_resource_group_{mock_suffix}

# Terraform Configuration Variables
TF_SKIP_CREDENTIAL_VALIDATION=true
TF_SKIP_METADATA_CHECK=true
CHECKPOINT_DISABLE=true
TF_VAR_environment={profile.environment}
TF_VAR_security_level={profile.security_level}
TF_VAR_generated_by=auto-arch-diagram
"""
        
        output_path.write_text(env_config)
        print(f"✅ Generated GitHub Actions environment for profile '{profile.name}'")
        print(f"   Output: {output_path}")
    
    def generate_docker_compose(self, profile: MockConfigProfile, output_path: Path) -> None:
        """Generate Docker Compose file for TerraVision with mock environment."""
        
        mock_suffix = self._get_mock_suffix(profile.security_level)
        
        compose_config = {
            "version": "3.8",
            "services": {
                "terravision": {
                    "image": "patrickchugh/terravision",
                    "command": [
                        "draw",
                        "--source", "/project",
                        "--format", "json",
                        "--outfile", "/project/analysis.json"
                    ],
                    "volumes": [
                        "./terraform:/project"
                    ],
                    "environment": [
                        f"AWS_ACCESS_KEY_ID=mock_access_key_{mock_suffix}",
                        f"AWS_SECRET_ACCESS_KEY=mock_secret_key_{mock_suffix}",
                        f"AWS_DEFAULT_REGION={profile.aws_region}",
                        f"TF_VAR_access_key=mock_access_key_{mock_suffix}",
                        f"TF_VAR_secret_key=mock_secret_key_{mock_suffix}",
                        f"TF_VAR_region={profile.aws_region}",
                        f"ARM_SUBSCRIPTION_ID=mock_subscription_id_{mock_suffix}",
                        f"ARM_CLIENT_ID=mock_client_id_{mock_suffix}",
                        f"ARM_CLIENT_SECRET=mock_client_secret_{mock_suffix}",
                        f"ARM_TENANT_ID=mock_tenant_id_{mock_suffix}",
                        f"TF_VAR_subscription_id=mock_subscription_id_{mock_suffix}",
                        f"TF_VAR_client_id=mock_client_id_{mock_suffix}",
                        f"TF_VAR_client_secret=mock_client_secret_{mock_suffix}",
                        f"TF_VAR_tenant_id=mock_tenant_id_{mock_suffix}",
                        f"GOOGLE_PROJECT_ID=mock_project_{mock_suffix}",
                        f"GOOGLE_APPLICATION_CREDENTIALS=mock_credentials_{mock_suffix}.json",
                        f"TF_VAR_project_id=mock_project_{mock_suffix}",
                        f"TF_VAR_credentials=mock_credentials_{mock_suffix}.json",
                        f"OCI_USER_ID=mock_user_id_{mock_suffix}",
                        f"OCI_FINGERPRINT=mock_fingerprint_{mock_suffix}",
                        f"OCI_PRIVATE_KEY=mock_private_key_{mock_suffix}",
                        f"OCI_TENANCY=mock_tenancy_{mock_suffix}",
                        f"TF_VAR_user_id=mock_user_id_{mock_suffix}",
                        f"TF_VAR_fingerprint=mock_fingerprint_{mock_suffix}",
                        f"TF_VAR_private_key=mock_private_key_{mock_suffix}",
                        f"TF_VAR_tenancy=mock_tenancy_{mock_suffix}",
                        f"IBMCLOUD_API_KEY=mock_api_key_{mock_suffix}",
                        f"IC_API_KEY=mock_api_key_{mock_suffix}",
                        f"TF_VAR_api_key=mock_api_key_{mock_suffix}",
                        f"TF_VAR_resource_group=mock_resource_group_{mock_suffix}",
                        "TF_SKIP_CREDENTIAL_VALIDATION=true",
                        "TF_SKIP_METADATA_CHECK=true",
                        "CHECKPOINT_DISABLE=true",
                        f"TF_VAR_environment={profile.environment}",
                        f"TF_VAR_security_level={profile.security_level}",
                        "TF_VAR_generated_by=auto-arch-diagram"
                    ],
                    "working_dir": "/project",
                    "profiles": {
                        profile.name: {
                            "environment": [
                                f"TF_VAR_environment={profile.environment}",
                                f"TF_VAR_security_level={profile.security_level}"
                            ]
                        }
                    }
                }
            }
        }
        
        # Write as YAML
        with open(output_path, 'w') as f:
            yaml.dump(compose_config, f, default_flow_style=False, indent=2)
        
        print(f"✅ Generated Docker Compose for profile '{profile.name}'")
        print(f"   Output: {output_path}")
        print(f"   Use: docker-compose --profile {profile.name} up terravision")
    
    def generate_all_configs(self, output_dir: Path) -> None:
        """Generate all mock configuration files for all profiles."""
        
        output_dir.mkdir(exist_ok=True)
        
        for profile_name, profile in self.profiles.items():
            profile_dir = output_dir / profile_name
            profile_dir.mkdir(exist_ok=True)
            
            # Generate Terraform providers
            tf_providers_path = profile_dir / "providers.tf"
            self.generate_terraform_providers(profile, tf_providers_path)
            
            # Generate GitHub Actions environment
            github_env_path = profile_dir / "github.env"
            self.generate_github_actions_env(profile, github_env_path)
            
            # Generate Docker Compose
            compose_path = profile_dir / "docker-compose.yml"
            self.generate_docker_compose(profile, compose_path)
            
            # Generate profile metadata
            metadata_path = profile_dir / "profile.json"
            with open(metadata_path, 'w') as f:
                json.dump(asdict(profile), f, indent=2)
        
        print(f"✅ Generated all configurations for {len(self.profiles)} profiles")
        print(f"   Output directory: {output_dir}")
    
    def _get_mock_suffix(self, security_level: str) -> str:
        """Get mock suffix based on security level."""
        suffixes = {
            "low": "dev",
            "medium": "staging", 
            "high": "prod"
        }
        return suffixes.get(security_level, "dev")
    
    def list_profiles(self) -> None:
        """List all available profiles."""
        print("📋 Available Mock Configuration Profiles:")
        print("=" * 60)
        
        for profile_name, profile in self.profiles.items():
            print(f"\n🏷️  {profile_name.upper()}")
            print(f"   Description: {profile.description}")
            print(f"   Environment: {profile.environment}")
            print(f"   Security Level: {profile.security_level}")
            print(f"   AWS Region: {profile.aws_region}")
            print(f"   Azure Location: {profile.azure_location}")
            print(f"   GCP Region: {profile.gcp_region}")
            if profile.oci_region:
                print(f"   OCI Region: {profile.oci_region}")
            if profile.ibm_region:
                print(f"   IBM Region: {profile.ibm_region}")


def main():
    """Main function for mock configuration generator."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate mock configurations for TerraVision integration")
    parser.add_argument(
        "--list-profiles",
        action="store_true",
        help="List all available configuration profiles"
    )
    parser.add_argument(
        "--profile",
        choices=["development", "staging", "production", "multi-cloud"],
        help="Configuration profile to use"
    )
    parser.add_argument(
        "--output-dir",
        default="mock-configs",
        help="Output directory for generated configurations"
    )
    parser.add_argument(
        "--generate-all",
        action="store_true",
        help="Generate configurations for all profiles"
    )
    parser.add_argument(
        "--terraform-only",
        action="store_true",
        help="Generate only Terraform provider configurations"
    )
    parser.add_argument(
        "--github-only",
        action="store_true",
        help="Generate only GitHub Actions environment files"
    )
    parser.add_argument(
        "--docker-only",
        action="store_true",
        help="Generate only Docker Compose files"
    )
    
    args = parser.parse_args()
    
    generator = MockConfigGenerator()
    
    if args.list_profiles:
        generator.list_profiles()
        return 0
    
    output_dir = Path(args.output_dir)
    
    if args.generate_all:
        generator.generate_all_configs(output_dir)
        return 0
    
    if args.profile:
        profile = generator.profiles[args.profile]
        output_dir.mkdir(exist_ok=True)
        
        if not args.github_only and not args.docker_only:
            tf_path = output_dir / "providers.tf"
            generator.generate_terraform_providers(profile, tf_path)
        
        if not args.terraform_only and not args.docker_only:
            github_path = output_dir / "github.env"
            generator.generate_github_actions_env(profile, github_path)
        
        if not args.terraform_only and not args.github_only:
            compose_path = output_dir / "docker-compose.yml"
            generator.generate_docker_compose(profile, compose_path)
        
        return 0
    
    parser.print_help()
    return 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
