flowchart LR
subgraph all_AWS[AWS]
  tf_aws_apigatewayv2_api_main["aws_apigatewayv2_api.main"]
  tf_aws_apigatewayv2_integration_api_handler["aws_apigatewayv2_integration.api_handler"]
  tf_aws_apigatewayv2_route_api_handler["aws_apigatewayv2_route.api_handler"]
  tf_aws_apigatewayv2_stage_main["aws_apigatewayv2_stage.main"]
  tf_aws_cloudwatch_log_group_api_logs["aws_cloudwatch_log_group.api_logs"]
  tf_aws_dynamodb_table_notifications["aws_dynamodb_table.notifications"]
  tf_aws_dynamodb_table_orders["aws_dynamodb_table.orders"]
  tf_aws_dynamodb_table_payments["aws_dynamodb_table.payments"]
  tf_aws_iam_role_lambda_role["aws_iam_role.lambda_role"]
  tf_aws_iam_role_policy_lambda_dynamodb_access["aws_iam_role_policy.lambda_dynamodb_access"]
  tf_aws_iam_role_policy_attachment_lambda_basic_execution["aws_iam_role_policy_attachment.lambda_basic_execution"]
  tf_aws_lambda_event_source_mapping_notification_sender_mapping["aws_lambda_event_source_mapping.notification_sender_mapping"]
  tf_aws_lambda_event_source_mapping_order_processor_mapping["aws_lambda_event_source_mapping.order_processor_mapping"]
  tf_aws_lambda_event_source_mapping_payment_processor_mapping["aws_lambda_event_source_mapping.payment_processor_mapping"]
  tf_aws_lambda_function_api_handler["aws_lambda_function.api_handler"]
  tf_aws_lambda_function_notification_sender["aws_lambda_function.notification_sender"]
  tf_aws_lambda_function_order_processor["aws_lambda_function.order_processor"]
  tf_aws_lambda_function_payment_processor["aws_lambda_function.payment_processor"]
  tf_aws_lambda_permission_api_gateway["aws_lambda_permission.api_gateway"]
  tf_aws_sns_topic_email_notifications["aws_sns_topic.email_notifications"]
  tf_aws_sns_topic_notification_events["aws_sns_topic.notification_events"]
  tf_aws_sns_topic_order_events["aws_sns_topic.order_events"]
  tf_aws_sns_topic_payment_events["aws_sns_topic.payment_events"]
  tf_aws_sns_topic_subscription_order_to_queue["aws_sns_topic_subscription.order_to_queue"]
  tf_aws_sns_topic_subscription_payment_to_queue["aws_sns_topic_subscription.payment_to_queue"]
  tf_aws_sqs_queue_order_dlq["aws_sqs_queue.order_dlq"]
  tf_aws_sqs_queue_order_queue["aws_sqs_queue.order_queue"]
  tf_aws_sqs_queue_payment_dlq["aws_sqs_queue.payment_dlq"]
  tf_aws_sqs_queue_payment_queue["aws_sqs_queue.payment_queue"]
  tf_aws_sqs_queue_policy_order_queue["aws_sqs_queue_policy.order_queue"]
  tf_aws_sqs_queue_policy_payment_queue["aws_sqs_queue_policy.payment_queue"]
end
tf_aws_apigatewayv2_api_main --> tf_aws_apigatewayv2_integration_api_handler
tf_aws_apigatewayv2_api_main --> tf_aws_apigatewayv2_route_api_handler
tf_aws_apigatewayv2_api_main --> tf_aws_apigatewayv2_stage_main
tf_aws_apigatewayv2_api_main --> tf_aws_lambda_permission_api_gateway
tf_aws_apigatewayv2_integration_api_handler --> tf_aws_apigatewayv2_route_api_handler
tf_aws_dynamodb_table_notifications --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_dynamodb_table_notifications --> tf_aws_lambda_function_notification_sender
tf_aws_dynamodb_table_orders --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_dynamodb_table_orders --> tf_aws_lambda_function_api_handler
tf_aws_dynamodb_table_orders --> tf_aws_lambda_function_order_processor
tf_aws_dynamodb_table_payments --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_dynamodb_table_payments --> tf_aws_lambda_event_source_mapping_notification_sender_mapping
tf_aws_dynamodb_table_payments --> tf_aws_lambda_function_payment_processor
tf_aws_iam_role_lambda_role --> tf_aws_iam_role_policy_attachment_lambda_basic_execution
tf_aws_iam_role_lambda_role --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_iam_role_lambda_role --> tf_aws_lambda_function_api_handler
tf_aws_iam_role_lambda_role --> tf_aws_lambda_function_notification_sender
tf_aws_iam_role_lambda_role --> tf_aws_lambda_function_order_processor
tf_aws_iam_role_lambda_role --> tf_aws_lambda_function_payment_processor
tf_aws_iam_role_policy_lambda_dynamodb_access --> tf_aws_lambda_event_source_mapping_notification_sender_mapping
tf_aws_iam_role_policy_lambda_dynamodb_access --> tf_aws_lambda_event_source_mapping_order_processor_mapping
tf_aws_iam_role_policy_lambda_dynamodb_access --> tf_aws_lambda_event_source_mapping_payment_processor_mapping
tf_aws_lambda_function_api_handler --> tf_aws_apigatewayv2_integration_api_handler
tf_aws_lambda_function_api_handler --> tf_aws_lambda_permission_api_gateway
tf_aws_lambda_function_notification_sender --> tf_aws_lambda_event_source_mapping_notification_sender_mapping
tf_aws_lambda_function_order_processor --> tf_aws_lambda_event_source_mapping_order_processor_mapping
tf_aws_lambda_function_payment_processor --> tf_aws_lambda_event_source_mapping_payment_processor_mapping
tf_aws_sns_topic_email_notifications --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sns_topic_email_notifications --> tf_aws_lambda_function_notification_sender
tf_aws_sns_topic_notification_events --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sns_topic_notification_events --> tf_aws_lambda_function_payment_processor
tf_aws_sns_topic_order_events --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sns_topic_order_events --> tf_aws_lambda_function_api_handler
tf_aws_sns_topic_order_events --> tf_aws_sns_topic_subscription_order_to_queue
tf_aws_sns_topic_order_events --> tf_aws_sqs_queue_policy_order_queue
tf_aws_sns_topic_payment_events --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sns_topic_payment_events --> tf_aws_lambda_function_order_processor
tf_aws_sns_topic_payment_events --> tf_aws_sns_topic_subscription_payment_to_queue
tf_aws_sns_topic_payment_events --> tf_aws_sqs_queue_policy_payment_queue
tf_aws_sqs_queue_order_dlq --> tf_aws_sqs_queue_order_queue
tf_aws_sqs_queue_order_queue --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sqs_queue_order_queue --> tf_aws_lambda_event_source_mapping_order_processor_mapping
tf_aws_sqs_queue_order_queue --> tf_aws_sns_topic_subscription_order_to_queue
tf_aws_sqs_queue_order_queue --> tf_aws_sqs_queue_policy_order_queue
tf_aws_sqs_queue_payment_dlq --> tf_aws_sqs_queue_payment_queue
tf_aws_sqs_queue_payment_queue --> tf_aws_iam_role_policy_lambda_dynamodb_access
tf_aws_sqs_queue_payment_queue --> tf_aws_lambda_event_source_mapping_payment_processor_mapping
tf_aws_sqs_queue_payment_queue --> tf_aws_sns_topic_subscription_payment_to_queue
tf_aws_sqs_queue_payment_queue --> tf_aws_sqs_queue_policy_payment_queue
